#!/bin/bash

echo Starting pre processing...
echo Make sure the datasets are in the right folders...
echo This process can triple data disk usage, be aware...

echo Generating Slope and Aspect from DEM...
gdal_dem.py
echo Slope and Aspect done...

echo Generating Sentinel-2 VRT...
gdal_vrt_sentinel2.py
echo VRT done...

echo Generating Sentinel-1 VRT...
gdal_vrt_sentinel1.py
echo VRT done...

echo Applying ROI...
gdal_clip.py
echo ROI done...

echo Upscaling to 10mx10m...
gdal_upscale.py
echo Upscaling done...

echo Generating Sentinel-2 indexes...
#gdal_index.py
echo Indexes done...