#!/bin/bash

echo Starting pre processing...
echo 'Make sure the datasets are in the right folders...'
echo This process can triple data disk usage, be aware...

echo Generating Slope and Aspect from DEM...
python gdal_processing_dem.py
echo Slope and Aspect done...

echo Clipping Sentinel-2...
python gdal_timeseries_s2_clip.py
echo Clipped Sentinel-2...

echo Clipping Sentinel-1...
python gdal_timeseries_s1_clip.py
echo Clipped Sentinel-1...

echo Idx Sentinel-2...
python gdal_timeseries_idx.py
echo Idxed Sentinel-2...

echo Processing Sentinel-1...
python gdal_timeseries_s1_processing.py
echo Processed Sentinel-1...

echo Processing Sentinel-2...
python gdal_timeseries_s2_processing.py
echo Processed Sentinel-2...

python gdal_val.py
